apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-cameras
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://localhost:1883
  - name: consumerID
    value: "{uuid}"
scopes:
  - trafficcontrolservice
