apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "keyvault-kfok64afnccvm"
  - name: azureTenantId
    value: "c916455d-ec0d-4d68-8fa7-3d0f896c6e3f"
  - name: azureClientId
    value: "a6d275bb-9a5c-41f1-ad70-3b9298fbc31c"
  - name: azureClientSecret
    value : "2Uy8Q~y8bXXHL3ywFsbNN_orMhkzkKudikxy3cMU"
