
# Publish speeding violation
POST http://127.0.0.1:6001/speedingviolation
Content-Type: application/json

{ "id": "foo", "vehicleId": "RK-546-V", "roadId": "A12", "violationInKmh": 15, "timestamp": "2020-09-20T08:33:41" }

### Get recent fines
GET http://127.0.0.1:6001/query/recent
Content-Type: application/json
